-- Development Seed Data for Clients
-- This file provides sample data for local development and testing
-- Safe to run multiple times (uses INSERT IGNORE)

-- Ensure we're working with the clients table
-- Insert sample clients for development

INSERT IGNORE INTO clients (
    client_code, company_name, legal_name, email, phone, website,
    address_line1, city, state_province, postal_code, country,
    tax_id, industry, client_type, status, credit_limit, payment_terms
) VALUES
(
    'CLI-001',
    'Acme Corporation',
    'Acme Corporation Inc.',
    'contact@acme-corp.example',
    '+1-555-0100',
    'https://acme-corp.example',
    '123 Business St',
    'New York',
    'NY',
    '10001',
    'US',
    'US-123456789',
    'Manufacturing',
    'business',
    'active',
    50000.00,
    30
),
(
    'CLI-002',
    'TechStart Solutions',
    'TechStart Solutions LLC',
    'info@techstart.example',
    '+1-555-0200',
    'https://techstart.example',
    '456 Innovation Ave',
    'San Francisco',
    'CA',
    '94102',
    'US',
    'US-987654321',
    'Technology',
    'business',
    'active',
    100000.00,
    60
),
(
    'CLI-003',
    'Global Traders Inc',
    'Global Traders Incorporated',
    'sales@globaltraders.example',
    '+44-20-1234-5678',
    'https://globaltraders.example',
    '789 Commerce Rd',
    'London',
    'England',
    'EC1A 1BB',
    'GB',
    'GB-123456789',
    'Retail',
    'business',
    'active',
    75000.00,
    45
),
(
    'CLI-004',
    'Green Energy Solutions',
    NULL,
    'contact@greenenergy.example',
    '+33-1-2345-6789',
    'https://greenenergy.example',
    '321 Eco Boulevard',
    'Paris',
    'Île-de-France',
    '75001',
    'FR',
    'FR-987654321',
    'Energy',
    'business',
    'active',
    150000.00,
    30
),
(
    'CLI-005',
    'John Smith Consulting',
    NULL,
    'john.smith@example.com',
    '+1-555-0300',
    'https://jsmith-consulting.example',
    '555 Consultant Lane',
    'Austin',
    'TX',
    '78701',
    'US',
    'US-555123456',
    'Consulting',
    'individual',
    'active',
    25000.00,
    15
),
(
    'CLI-006',
    'City Government Services',
    'City of Springfield',
    'procurement@springfield.gov',
    '+1-555-0400',
    'https://springfield.gov',
    '1000 Main Street',
    'Springfield',
    'IL',
    '62701',
    'US',
    'US-GOV-12345',
    'Government',
    'government',
    'active',
    200000.00,
    90
),
(
    'CLI-007',
    'Nonprofit Health Initiative',
    'Health for All Foundation',
    'info@healthforall.example',
    '+1-555-0500',
    'https://healthforall.example',
    '222 Care Street',
    'Boston',
    'MA',
    '02101',
    'US',
    'US-NPO-98765',
    'Healthcare',
    'nonprofit',
    'active',
    30000.00,
    60
),
(
    'CLI-008',
    'Inactive Corp',
    'Inactive Corporation Ltd',
    'old@inactive.example',
    NULL,
    NULL,
    '999 Old Building',
    'Detroit',
    'MI',
    '48201',
    'US',
    'US-999999999',
    'Defunct',
    'business',
    'inactive',
    0.00,
    NULL
);

-- Verify seed data
SELECT 
    COUNT(*) as total_clients,
    SUM(CASE WHEN status = 'active' THEN 1 ELSE 0 END) as active_clients,
    SUM(CASE WHEN status = 'inactive' THEN 1 ELSE 0 END) as inactive_clients
FROM clients;
